export const SDK_DOCS_BASE =
  "https://web-assets.waze.com/wme_sdk_docs/production/latest/classes/index.SDK.";

export interface MethodEntry {
  name: string;
}

export interface PropertyEntry {
  name: string;
  docsClass: string | string[];
}

export interface ModuleEntry {
  label: string;
  accessor: string;
  docsClass: string;
  properties?: PropertyEntry[];
  methods: MethodEntry[];
}

export function getDocsUrl(docsClass: string, methodName: string): string {
  return `${SDK_DOCS_BASE}${docsClass}.html#${methodName.toLowerCase()}`;
}

export const SDK_REGISTRY: ModuleEntry[] = [
  {
    label: "WmeSDK",
    accessor: "",
    docsClass: "WmeSDK",
    properties: [
      { name: "DataModel", docsClass: "DataModel" },
      { name: "Editing", docsClass: "Editing" },
      {
        name: "Errors",
        docsClass: [
          "DataModelNotFoundError",
          "InvalidStateError",
          "ValidationError",
          "WMEError",
        ],
      },
      { name: "Events", docsClass: "SdkEventBus" },
      { name: "LayerSwitcher", docsClass: "LayerSwitcher" },
      { name: "Map", docsClass: "Map" },
      { name: "Settings", docsClass: "Settings" },
      { name: "Shortcuts", docsClass: "Shortcuts" },
      { name: "Sidebar", docsClass: "Sidebar" },
      { name: "State", docsClass: "WmeState" },
    ],
    methods: [
      { name: "getScriptId" },
      { name: "getScriptName" },
      { name: "getSDKVersion" },
      { name: "getWMEBackEndVersion" },
      { name: "getWMEVersion" },
      { name: "isBetaEnvironment" },
    ],
  },
  {
    label: "DataModel",
    accessor: "DataModel",
    docsClass: "DataModel",
    properties: [
      { name: "BigJunctions", docsClass: "BigJunctions" },
      { name: "Cities", docsClass: "Cities" },
      { name: "Countries", docsClass: "Countries" },
      { name: "EditSuggestions", docsClass: "EditSuggestions" },
      { name: "HouseNumbers", docsClass: "HouseNumbers" },
      { name: "Junctions", docsClass: "Junctions" },
      { name: "MajorTrafficEvents", docsClass: "MajorTrafficEvents" },
      { name: "ManagedAreas", docsClass: "ManagedAreas" },
      { name: "MapComments", docsClass: "MapComments" },
      { name: "MapProblems", docsClass: "MapProblems" },
      { name: "MapUpdateRequests", docsClass: "MapUpdateRequests" },
      { name: "Nodes", docsClass: "Nodes" },
      { name: "PermanentHazards", docsClass: "PermanentHazards" },
      { name: "RestrictedDrivingAreas", docsClass: "RestrictedDrivingAreas" },
      { name: "RoadClosures", docsClass: "RoadClosures" },
      { name: "Segments", docsClass: "Segments" },
      { name: "States", docsClass: "States" },
      { name: "Streets", docsClass: "Streets" },
      { name: "TurnClosures", docsClass: "TurnClosures" },
      { name: "Turns", docsClass: "Turns" },
      { name: "Users", docsClass: "Users" },
      { name: "Venues", docsClass: "Venues" },
    ],
    methods: [
      // { name: "isDeletable" },
      // { name: "isDeleted" },
      // { name: "isNew" },
      { name: "refreshData" },
    ],
  },
  {
    label: "Editing",
    accessor: "Editing",
    docsClass: "Editing",
    methods: [
      { name: "clearSelection" },
      { name: "getCurrentSaveMode" },
      { name: "getRedoChangesCount" },
      { name: "getSelection" },
      { name: "getUnsavedChangesCount" },
      { name: "isDrawingInProgress" },
      { name: "isEditingAllowed" },
      { name: "isEditingHouseNumbers" },
      { name: "isPracticeModeOn" },
      { name: "isSnapshotModeOn" },
      { name: "lockEditing" },
      { name: "redo" },
      // { name: "releaseEditingLock" },
      { name: "save" },
      // { name: "setSelection" },
      { name: "undo" },
      { name: "undoAll" },
    ],
  },
  {
    label: "Map",
    accessor: "Map",
    docsClass: "Map",
    properties: [
      { name: "MAX_ZOOM_LEVEL", docsClass: "ZoomLevel" },
      { name: "MIN_ZOOM_LEVEL", docsClass: "ZoomLevel" },
    ],
    methods: [
      // { name: "addFeaturesToLayer" },
      // { name: "addFeatureToLayer" },
      // { name: "addLayer" },
      // { name: "addStyleRuleToLayer" },
      // { name: "addTileLayer" },
      // { name: "centerMapOnGeometry" },
      // { name: "dangerouslyAddFeaturesToLayerWithoutValidation" },
      // { name: "disablePolygonResize" },
      // { name: "disablePolygonRotation" },
      // { name: "disableSelectionToggling" },
      // { name: "drawLine" },
      // { name: "drawPolygon" },
      // { name: "enablePolygonResize" },
      // { name: "enablePolygonRotation" },
      // { name: "enableSelectionToggling" },
      // { name: "getFeatureDomElement" },
      // { name: "getLayerOpacity" },
      // { name: "getLayerZIndex" },
      { name: "getLiveMapLink" },
      // { name: "getLonLatFromMapPixel" },
      // { name: "getLonLatFromPixel" },
      { name: "getMapCenter" },
      { name: "getMapExtent" },
      // { name: "getMapPixelFromLonLat" },
      { name: "getMapResolution" },
      { name: "getMapViewportElement" },
      { name: "getPermalink" },
      // { name: "getPixelFromLonLat" },
      { name: "getZoomLevel" },
      // { name: "isLayerVisible" },
      { name: "isStreetViewActive" },
      // { name: "redrawLayer" },
      // { name: "removeAllFeaturesFromLayer" },
      // { name: "removeFeatureFromLayer" },
      // { name: "removeFeaturesFromLayer" },
      // { name: "removeLayer" },
      // { name: "setLayerOpacity" },
      // { name: "setLayerVisibility" },
      // { name: "setLayerZIndex" },
      // { name: "setMapCenter" },
      // { name: "setZoomLevel" },
      { name: "zoomIn" },
      { name: "zoomOut" },
      // { name: "zoomToExtent" },
    ],
  },
  {
    label: "Settings",
    accessor: "Settings",
    docsClass: "Settings",
    methods: [
      { name: "getLocale" },
      { name: "getRegionCode" },
      { name: "getUserSettings" },
      // { name: "setRegionCode" },
      // { name: "setUserSettings" },
    ],
  },
  {
    label: "Shortcuts",
    accessor: "Shortcuts",
    docsClass: "Shortcuts",
    methods: [
      // { name: "areShortcutKeysInUse" },
      // { name: "createShortcut" },
      // { name: "deleteShortcut" },
      { name: "getAllShortcuts" },
      { name: "isShortcutRegistered" },
    ],
  },
  {
    label: "WmeState",
    accessor: "State",
    docsClass: "WmeState",
    methods: [
      { name: "getManagedCountries" },
      { name: "getUserInfo" },
      { name: "isInitialized" },
      { name: "isInitialMapDataLoaded" },
      { name: "isLoggedIn" },
      { name: "isMapLoading" },
      { name: "isReady" },
    ],
  },
  {
    label: "BigJunctions",
    accessor: "DataModel.BigJunctions",
    docsClass: "BigJunctions",
    methods: [
      { name: "getAll" },
      // { name: "getAllPossibleTurns" },
      // { name: "getById" },
    ],
  },
  {
    label: "Cities",
    accessor: "DataModel.Cities",
    docsClass: "Cities",
    methods: [
      // { name: "addCity" },
      { name: "getAll" },
      // { name: "getById" },
      // { name: "getCity" },
      { name: "getTopCity" },
    ],
  },
  {
    label: "Countries",
    accessor: "DataModel.Countries",
    docsClass: "Countries",
    methods: [
      { name: "getAll" },
      // { name: "getById" },
      { name: "getTopCountry" },
    ],
  },
  {
    label: "EditSuggestions",
    accessor: "DataModel.EditSuggestions",
    docsClass: "EditSuggestions",
    methods: [
      { name: "getAll" },
      // { name: "getById" },
      // { name: "getEditSuggestionChanges" },
    ],
  },
  {
    label: "HouseNumbers",
    accessor: "DataModel.HouseNumbers",
    docsClass: "HouseNumbers",
    methods: [
      // { name: "addHouseNumber" },
      { name: "clearHouseNumbers" },
      // { name: "deleteHouseNumber" },
      // { name: "fetchHouseNumbers" },
      // { name: "moveHouseNumber" },
      // { name: "moveHouseNumberFractionPoint" },
      // { name: "updateHouseNumber" },
    ],
  },
  {
    label: "Junctions",
    accessor: "DataModel.Junctions",
    docsClass: "Junctions",
    methods: [
      { name: "getAll" },
      // { name: "getById" },
    ],
  },
  {
    label: "MajorTrafficEvents",
    accessor: "DataModel.MajorTrafficEvents",
    docsClass: "MajorTrafficEvents",
    methods: [
      { name: "getAll" },
      // { name: "getById" },
    ],
  },
  {
    label: "ManagedAreas",
    accessor: "DataModel.ManagedAreas",
    docsClass: "ManagedAreas",
    methods: [
      { name: "getAll" },
      // { name: "getById" },
    ],
  },
  {
    label: "MapComments",
    accessor: "DataModel.MapComments",
    docsClass: "MapComments",
    methods: [
      // { name: "addComment" },
      { name: "getAll" },
      // { name: "getById" },
      // { name: "updateComment" },
    ],
  },
  {
    label: "MapProblems",
    accessor: "DataModel.MapProblems",
    docsClass: "MapProblems",
    methods: [
      { name: "getAll" },
      // { name: "getById" },
    ],
  },
  {
    label: "MapUpdateRequests",
    accessor: "DataModel.MapUpdateRequests",
    docsClass: "MapUpdateRequests",
    methods: [
      // { name: "addComment" },
      { name: "getAll" },
      // { name: "getById" },
      // { name: "getUpdateRequestDetails" },
      // { name: "updateResolutionState" },
    ],
  },
  {
    label: "Nodes",
    accessor: "DataModel.Nodes",
    docsClass: "Nodes",
    methods: [
      // { name: "allowNodeTurns" },
      // { name: "canEdit" },
      // { name: "canEditTurns" },
      { name: "getAll" },
      // { name: "getById" },
      // { name: "isVirtual" },
      // { name: "moveNode" },
    ],
  },
  {
    label: "PermanentHazards",
    accessor: "DataModel.PermanentHazards",
    docsClass: "PermanentHazards",
    methods: [
      { name: "getAllCameras" },
      // { name: "getCameraById" },
    ],
  },
  {
    label: "RestrictedDrivingAreas",
    accessor: "DataModel.RestrictedDrivingAreas",
    docsClass: "RestrictedDrivingAreas",
    methods: [
      { name: "getAll" },
      // { name: "getById" },
    ],
  },
  {
    label: "RoadClosures",
    accessor: "DataModel.RoadClosures",
    docsClass: "RoadClosures",
    methods: [
      // { name: "addClosure" },
      { name: "getAll" },
      // { name: "getById" },
    ],
  },
  {
    label: "Segments",
    accessor: "DataModel.Segments",
    docsClass: "Segments",
    methods: [
      // { name: "addAlternateStreet" },
      // { name: "addIntersection" },
      // { name: "addSegment" },
      { name: "getAll" },
      // { name: "getById" },
    ],
  },
  {
    label: "States",
    accessor: "DataModel.States",
    docsClass: "States",
    methods: [
      { name: "getAll" },
      { name: "getAllWithoutDefault" },
      // { name: "getById" },
      { name: "getTopState" },
      { name: "hasNonDefaultStates" },
    ],
  },
  {
    label: "Streets",
    accessor: "DataModel.Streets",
    docsClass: "Streets",
    methods: [
      // { name: "addStreet" },
      { name: "getAll" },
      // { name: "getById" },
      // { name: "getStreet" },
      // { name: "updateStreet" },
    ],
  },
  {
    label: "TurnClosures",
    accessor: "DataModel.TurnClosures",
    docsClass: "TurnClosures",
    methods: [
      // { name: "addClosure" },
      { name: "getAll" },
      // { name: "getById" },
    ],
  },
  {
    label: "Turns",
    accessor: "DataModel.Turns",
    docsClass: "Turns",
    methods: [
      // { name: "addClosure" },
      { name: "getAll" },
      // { name: "getById" },
    ],
  },
  {
    label: "Users",
    accessor: "DataModel.Users",
    docsClass: "Users",
    methods: [
      // { name: "getLocalizedUserProfile" },
      // { name: "getUserProfile" },
      // { name: "getUserProfileLink" },
    ],
  },
  {
    label: "Venues",
    accessor: "DataModel.Venues",
    docsClass: "Venues",
    properties: [
      { name: "ChargingStation", docsClass: "Venues" },
      { name: "ParkingLot", docsClass: "Venues" },
    ],
    methods: [
      // { name: "addVenue" },
      // { name: "deleteImage" },
      // { name: "deleteVenue" },
      // { name: "deleteVenue" },
      // { name: "getAddress" },
      { name: "getAll" },
      { name: "getAllVenueCategories" },
      // { name: "getById" },
      { name: "getChargingStationBrands" },
      { name: "getGasStationBrands" },
      { name: "getParkingLotBrands" },
      // { name: "getParkingLotType" },
      { name: "getVenueMainCategories" },
      { name: "getVenueSubCategories" },
      // { name: "hasPermissions" },
      // { name: "replaceNavigationPoints" },
      // { name: "showVenueUpdateRequestDialog" },
      // { name: "updateAddress" },
      // { name: "updateAddress" },
      // { name: "updateVenueIsResidential" },
      // { name: "updateVenueUpdateRequest" },
    ],
  },
];
